#pragma once

#include "NativeGameplayTags.h"

namespace GarTags
{
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
}

namespace GarDesiredStateTags
{
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
}

namespace GarDesiredRotationModeTags
{
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(VelocityDirection)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ViewDirection)
}

namespace GarDesiredStanceTags
{
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Standing)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouching)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lying)
}

namespace GarDesiredGaitTags
{
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walking)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Running)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprinting)
}

namespace GarViewModeTags
{
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FirstPerson)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ThirdPerson)
}

namespace GarLocomotionModeTags
{
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InAir)
}

namespace GarRotationModeTags
{
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(VelocityDirection)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ViewDirection)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Aiming)
}

namespace GarAimingModeTags
{
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AimDownSight)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HipFire)
}

namespace GarStanceTags
{
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Standing)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouching)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lying)
}

namespace GarGaitTags
{
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walking)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Running)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprinting)
}

namespace GarOverlayModeTags
{
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Default)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Injured)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HandsTied)
}

namespace GarLocomotionActionTags
{
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rolling)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Landing)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Traversal)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GettingUp)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GettingDown)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FreeFalling)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unconsious)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dying)
}

namespace GarStateFlagTags
{
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LeftShoulder) // Removal? no reference in source
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FacingUpward)
}

namespace GarTraversalActionTags
{
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Vault)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hurdle)
	GAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mantle)
}
