#pragma once

#include "NativeGameplayTags.h"

namespace GarCameraTags
{
	GARCAMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
}

namespace GarCameraViewModeTags
{
	GARCAMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	GARCAMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FirstPerson)
	GARCAMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ThirdPerson)
}

namespace GarCameraShoulderModeTags
{
	GARCAMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	GARCAMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Center)
	GARCAMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Left)
	GARCAMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Right)
}
